"""Lock file management."""

from __future__ import annotations

import tomllib
from typing import TYPE_CHECKING, Any

from gdpm.models.lock import LockEntry

if TYPE_CHECKING:
    from pathlib import Path


def read_lockfile(path: Path) -> list[LockEntry]:
    if not path.exists():
        return []

    with open(path, "rb") as f:
        data: dict[str, Any] = tomllib.load(f)

    entries: list[LockEntry] = []
    for pkg in data.get("package", []):
        entries.append(
            LockEntry(
                name=pkg.get("name", ""),
                version=pkg.get("version", ""),
                source=pkg.get("source", ""),
            )
        )
    return entries


def write_lockfile(entries: list[LockEntry], path: Path) -> None:
    lines: list[str] = []
    lines.append("# This file is auto-generated by gdpm. Do not edit manually.")
    lines.append("version = 1")
    lines.append("")

    for entry in sorted(entries, key=lambda e: e.name):
        lines.append("[[package]]")
        lines.append(f'name = "{entry.name}"')
        lines.append(f'version = "{entry.version}"')
        lines.append(f'source = "{entry.source}"')
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def find_lockfile(project_root: Path) -> Path:
    return project_root / "gdpm.lock"
