"""Installer protocol."""

from __future__ import annotations

from typing import Protocol


class InstallerProtocol(Protocol):
    def install(self, name: str, version: str) -> None: ...
    def remove(self, name: str) -> None: ...
    def is_installed(self, name: str) -> bool: ...
    def installed_version(self, name: str) -> str | None: ...
